In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('penguins')
df



species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [3]:
df.shape

(344, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [5]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
df.dropna(inplace = True)

In [7]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

# Feature Engineering

#One hot encoding transforming categorical data into numeric

In [8]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [9]:
sex = pd.get_dummies(df['sex'], drop_first = True)
sex

Male
0       1
1       0
2       0
4       0
5       1
..    ...
338     0
340     0
341     1
342     0
343     1

[333 rows x 1 columns]

In [10]:
island = pd.get_dummies(df['island'], drop_first = True)
island

Dream  Torgersen
0        0          1
1        0          1
2        0          1
4        0          1
5        0          1
..     ...        ...
338      0          0
340      0          0
341      0          0
342      0          0
343      0          0

[333 rows x 2 columns]

In [11]:
df = pd.concat([df, sex, island], axis = 1)
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  Male  Dream  Torgersen  
0         3750.0    Male     1      0          1  
1         3800.0  Female     0      0          1  
2         3250.0  Female     0      0          1  
4         3450.0  Female     0      0          1  
5         3650.0    Male     1      0          1  
..           ...     ...   ...    ...        ...  
338       4925.0  Female     0      0          0  
340       4850.0  Female     0      0          0  
341       5750.0    Male     1      0          0  
342       5200.0  Female     0      0          0  
343       5400.0    Male     1      0          0  

[333 rows x 10 columns]

In [12]:
df = df.drop(df.columns[1:2], 1)
df

C:\Users\user\AppData\Local\Temp\ipykernel_9572\2353451500.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(df.columns[1:2], 1)


species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0    Adelie            39.1           18.7              181.0       3750.0   
1    Adelie            39.5           17.4              186.0       3800.0   
2    Adelie            40.3           18.0              195.0       3250.0   
4    Adelie            36.7           19.3              193.0       3450.0   
5    Adelie            39.3           20.6              190.0       3650.0   
..      ...             ...            ...                ...          ...   
338  Gentoo            47.2           13.7              214.0       4925.0   
340  Gentoo            46.8           14.3              215.0       4850.0   
341  Gentoo            50.4           15.7              222.0       5750.0   
342  Gentoo            45.2           14.8              212.0       5200.0   
343  Gentoo            49.9           16.1              213.0       5400.0   

        sex  Male  Dream  Torgersen  
0      Male     1      0          1  
1    Female     0      0          1  
2    Female     0      0          1  
4    Female     0      0          1  
5      Male     1      0          1  
..      ...   ...    ...        ...  
338  Female     0      0          0  
340  Female     0      0          0  
341    Male     1      0          0  
342  Female     0      0          0  
343    Male     1      0          0  

[333 rows x 9 columns]

In [13]:
df = df.drop(df.columns[5:6],1)
df

C:\Users\user\AppData\Local\Temp\ipykernel_9572\2718102637.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(df.columns[5:6],1)


species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0    Adelie            39.1           18.7              181.0       3750.0   
1    Adelie            39.5           17.4              186.0       3800.0   
2    Adelie            40.3           18.0              195.0       3250.0   
4    Adelie            36.7           19.3              193.0       3450.0   
5    Adelie            39.3           20.6              190.0       3650.0   
..      ...             ...            ...                ...          ...   
338  Gentoo            47.2           13.7              214.0       4925.0   
340  Gentoo            46.8           14.3              215.0       4850.0   
341  Gentoo            50.4           15.7              222.0       5750.0   
342  Gentoo            45.2           14.8              212.0       5200.0   
343  Gentoo            49.9           16.1              213.0       5400.0   

     Male  Dream  Torgersen  
0       1      0          1  
1       0      0          1  
2       0      0          1  
4       0      0          1  
5       1      0          1  
..    ...    ...        ...  
338     0      0          0  
340     0      0          0  
341     1      0          0  
342     0      0          0  
343     1      0          0  

[333 rows x 8 columns]

In [14]:
df1 = df.rename(columns = {'Male': 'sex'})
df1

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0    Adelie            39.1           18.7              181.0       3750.0   
1    Adelie            39.5           17.4              186.0       3800.0   
2    Adelie            40.3           18.0              195.0       3250.0   
4    Adelie            36.7           19.3              193.0       3450.0   
5    Adelie            39.3           20.6              190.0       3650.0   
..      ...             ...            ...                ...          ...   
338  Gentoo            47.2           13.7              214.0       4925.0   
340  Gentoo            46.8           14.3              215.0       4850.0   
341  Gentoo            50.4           15.7              222.0       5750.0   
342  Gentoo            45.2           14.8              212.0       5200.0   
343  Gentoo            49.9           16.1              213.0       5400.0   

     sex  Dream  Torgersen  
0      1      0          1  
1      0      0          1  
2      0      0          1  
4      0      0          1  
5      1      0          1  
..   ...    ...        ...  
338    0      0          0  
340    0      0          0  
341    1      0          0  
342    0      0          0  
343    1      0          0  

[333 rows x 8 columns]

# Splitting the dataset into training and test data

In [15]:
#seperate the target variable from the features/predictor
X = df.drop('species', axis = 1)
y = df['species']

In [16]:
X,y

(     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Male  \
 0              39.1           18.7              181.0       3750.0     1   
 1              39.5           17.4              186.0       3800.0     0   
 2              40.3           18.0              195.0       3250.0     0   
 4              36.7           19.3              193.0       3450.0     0   
 5              39.3           20.6              190.0       3650.0     1   
 ..              ...            ...                ...          ...   ...   
 338            47.2           13.7              214.0       4925.0     0   
 340            46.8           14.3              215.0       4850.0     0   
 341            50.4           15.7              222.0       5750.0     1   
 342            45.2           14.8              212.0       5200.0     0   
 343            49.9           16.1              213.0       5400.0     1   
 
      Dream  Torgersen  
 0        0          1  
 1        0          1  

In [17]:
from sklearn.preprocessing import LabelEncoder

la = LabelEncoder()

y = la.fit_transform(y)

y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [20]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Male  \
165            52.0           18.1              201.0       4050.0     1   
156            52.7           19.8              197.0       3725.0     1   
112            39.7           17.7              193.0       3200.0     0   
220            46.1           13.2              211.0       4500.0     0   
96             38.1           18.6              190.0       3700.0     0   
..              ...            ...                ...          ...   ...   
332            43.5           15.2              213.0       4650.0     0   
198            50.1           17.9              190.0       3400.0     0   
123            41.4           18.5              202.0       3875.0     1   
53             42.0           19.5              200.0       4050.0     1   
178            50.5           18.4              200.0       3400.0     0   

     Dream  Torgersen  
165      1          0  
156      1          0  
112      0     

In [21]:
print('X_train', X_train.shape)
print('X_test', X_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)

X_train (233, 7)
X_test (100, 7)
y_train (233,)
y_test (100,)


# Training Random Forest Classification On Training Set

In [22]:
#Creating the model

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 7, criterion = 'entropy', random_state = 0) #n_estimator = number of decision
                                                                                               # trees
#you can keep changing the n_estimator(number of decision tree) and the criterion(entropy or gini) to get the accuracy scores.

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report, accuracy_score

In [24]:
df.species.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [25]:
cn = confusion_matrix(y_test, y_pred)
print(cn)

#               Predicted values
#Actual values  0     1      2

#    0          48    0      0    Here the model predicted that there were only 48 Adelie species and actually there were
#                                 48, NO false predictions(hence 0= Chinstrap, 0 = Gentoo).

#    1          1     15     0   Here the model predicted that there were 15 Chinstrap species and actually there were
#                                15, false prediction = 1 Adelie.

#    2          1     0     36   Here the model predicted that there were 36 Gentoo species and in reality ,
                                 # there were 36, false preiction = 1 Adelie.
    
                                 #In all, there was only two false predictions.

[[48  0  0]
 [ 1 15  0]
 [ 0  0 36]]


In [26]:
accuracy_score(y_test, y_pred) # 99% accuracy

0.99

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        48
           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        36

    accuracy                           0.99       100
   macro avg       0.99      0.98      0.99       100
weighted avg       0.99      0.99      0.99       100



# Try With Different Number Of Trees And gini Criteria

In [28]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 7, criterion = 'gini', random_state = 0) #criterion changed to gini
                                                                                               
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [29]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [30]:
confusion_matrix(y_test, y_pred)


array([[48,  0,  0],
       [ 2, 14,  0],
       [ 0,  0, 36]], dtype=int64)

In [31]:
accuracy_score(y_test, y_pred)

0.98

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100

